### ISSUE TITLE
replay_dataset

### ISSUE THREAD

**Issue by 233function** [zhiyuanhubj/LongRecipe#3]
你好，第二步训练时的replay_dataset的地址有么

**Comment by zhiyuanhubj** [comment]
Hi, here are the link for these datasets for replaying.

WizardLM-evol-instruct-70k: https://huggingface.co/datasets/WizardLMTeam/WizardLM_evol_instruct_70k, MagicoderOSS-Instruct-75K: https://huggingface.co/datasets/ise-uiuc/Magicoder-OSS-Instruct-75K
